DROP DATABASE IF EXISTS projet_uf_db;

CREATE DATABASE projet_uf_db;

USE projet_uf_db;

CREATE TABLE message (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  mail VARCHAR(50) NOT NULL,
  pseudo VARCHAR(20) NULL,
  msg TEXT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE login_admin (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  pseudo VARCHAR(20) NOT NULL,
  password VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE competences (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom_comp VARCHAR(30) NOT NULL,
  image VARCHAR(50) NOT NULL,
  pourcentage VARCHAR(10) NOT NULL,
  PRIMARY KEY (id)
)

ENGINE = INNODB;
